#markdown: rdiscount
markdown: kramdown
#markdown: redcarpet
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: Joy | Thinkings & Works
host: jiych.github.io
desc: Thinkings & Works

custom:
    category:
        linux: linux 
        ruby: ruby 
        tips: tips 
        life: life
        
    categories:
      - name: linux 
        title: linux

      - name: tips 
        title: tips

      - name: life 
        title: life 

      - name: ruby 
        title: ruby 

    scrollingLoadCount: 0

meta:
    author:
        name: jiych
        email: jiych.guru@gmail.com
        disqus: jiych 			                # Disqus缩略标识
        gcse: 003846770488047756774:-bbnpqgyp2y     # Google自定义搜索标识ID
        #dont fork me!!
        #github: jiych              			    # GitHub账号
        gravatar: 0781da482ba53cb4b6eac7e11d19f0f1  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
