#markdown: rdiscount
markdown: kramdown
#markdown: redcarpet
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: Joy
host: jiych.github.io
desc: Thinkings & works

custom:
    category:
        linux: linux 
        tips: tips 
        life: life
        
    categories:
      - name: linux 
        title: linux

      - name: tips 
        title: tips

      - name: life 
        title: life 

scrollingLoadCount: 0

meta:
    author:
        name: jiych
        email: jiych.guru@gmail.com
        disqus: jiych 			                # Disqus缩略标识
        gcse: 002980071478006019237:bcmd-n00ura     # Google自定义搜索标识ID
        github: jiych              			    # GitHub账号
        gravatar: b1b40161ebd87b851d3eb65e870f1213  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
